/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChipTag: typeof import('./src/components/ChipTag.vue')['default']
    DiscordLogo: typeof import('./src/components/DiscordLogo.vue')['default']
    FlowinityLogo: typeof import('./src/components/FlowinityLogo.vue')['default']
    FlowinityWordmark: typeof import('./src/components/FlowinityWordmark.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
